[package]
name = "bbs-revocation"
version = "0.1.0"
authors = ["Andrew Whitehead <cywolf@gmail.com>"]
edition = "2018"

[dependencies]
bbs = "0.4"
blake2 = "0.8"
ff-zeroize = "0.6"
heapless = "0.7"
pairing-plus = "0.19"
rand = "0.7"
